export const ASSET_CATEGORIES = [
  "DEV_KIT", "MONITOR", "TV", "CPU", "KEYBOARD", "MOUSE", "CAMERA",
  "MEMORY_CARD", "PROJECTOR", "RECORDER", "ROUTER", "SIMULATOR",
  "TABLET", "VR", "PRINTER", "SWITCH", "HARD_DRIVE", "AUDIO",
  "VIDEO_CAMERA", "SPEAKER"
];
