// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Built from the same DATABASE_HOST/USER/PASSWORD/NAME vars server.ts and prisma.ts
// use at runtime, so there's one place to set credentials instead of two.
const {
  DATABASE_HOST = "localhost",
  DATABASE_USER = "root",
  DATABASE_PASSWORD = "",
  DATABASE_NAME = "AdRIC_DB",
} = process.env;

// Built from parts rather than reading DATABASE_URL directly — keeps a single
// source of truth with server.ts/prisma.ts instead of two strings to keep in sync.
const datasourceUrl = `mysql://${DATABASE_USER}:${encodeURIComponent(DATABASE_PASSWORD)}@${DATABASE_HOST}:3306/${DATABASE_NAME}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
